### ISSUE TITLE
SerialNixieDriver

### ISSUE THREAD

**Issue by tonyp7** [marcinsaj/Nixie-Tube-Driver#1]
Hello,

I am fairly certain your nixie driver is compatible with the library I had made for my own shift register based driver:
https://github.com/tonyp7/SerialNixieDriver

It uses a simple SPI or SoftwareSerial instead of manually bitbanging.

Cheers

**Comment by marcinsaj** [comment]
Hi,
thanks for the tip. I will check it.

**Comment by vascobarbosa** [comment]
they are compatible,

rck => en_pin
sck => clk_pin
dataPin => din_pin
